name: Bug report (engine)
labels: [bug, engine]
body:
  - type: textarea
    attributes: { label: What happened?, description: Steps + expected vs actual }
  - type: textarea
    attributes: { label: Minimal repro, description: Code or move list }
