name: Rules question / clarification
labels: [rules]
body:
  - type: textarea
    attributes: { label: Section/line, description: Quote the rule text }
  - type: textarea
    attributes: { label: Proposed wording, description: Suggest exact change }
