#!/usr/bin/env python3
"""
LaTeX Print Standards Script
Automates adding bleed, crop marks, and print-ready formatting to LaTeX documents.

Usage:
    python latex_print_standards.py input.tex --format a4 --bleed 3mm
    python latex_print_standards.py input.tex --format us_letter --bleed 0.125in
    python latex_print_standards.py input.tex --format drivethru_6x9 --bleed 0.125in

Options:
    --format     : a4, us_letter, drivethru_6x9, drivethru_8x11, custom
    --bleed      : 3mm, 0.125in (default: 3mm)
    --output     : output filename (default: input_printed.tex)
    --titlepage  : add a properly formatted title page
    --cropmarks  : add crop marks (default: true)
    --safezone   : safe zone margin (default: 6mm)
    --verbose    : print verbose output
    --book       : use book class instead of article
    --fontsize   : font size (default: 11pt)
    --dry-run    : show what would be changed without writing
"""

import os
import sys
import re
import argparse
from pathlib import Path
from datetime import datetime

# =============================================================================
# Configuration
# =============================================================================

# Standard page sizes with trim and bleed
PAGE_SIZES = {
    'a4': {
        'name': 'A4',
        'trim_width_mm': 210,
        'trim_height_mm': 297,
        'trim_width_in': '210mm',
        'trim_height_in': '297mm',
        'description': 'Standard A4 (210mm × 297mm)',
        'print_width': '216mm',   # A4 + 6mm bleed
        'print_height': '303mm',
    },
    'us_letter': {
        'name': 'US Letter',
        'trim_width_mm': 215.9,
        'trim_height_mm': 279.4,
        'trim_width_in': '8.5in',
        'trim_height_in': '11in',
        'description': 'US Letter (8.5in × 11in)',
        'print_width': '8.75in',   # 8.5 + 0.25 bleed
        'print_height': '11.25in',
    },
    'drivethru_6x9': {
        'name': 'DriveThruRPG 6x9',
        'trim_width_mm': 152.4,
        'trim_height_mm': 228.6,
        'trim_width_in': '6in',
        'trim_height_in': '9in',
        'description': 'DriveThruRPG 6×9 (152mm × 229mm)',
        'print_width': '6.25in',
        'print_height': '9.25in',
    },
    'drivethru_8x11': {
        'name': 'DriveThruRPG 8.5x11',
        'trim_width_mm': 215.9,
        'trim_height_mm': 279.4,
        'trim_width_in': '8.5in',
        'trim_height_in': '11in',
        'description': 'DriveThruRPG 8.5×11 (215mm × 279mm)',
        'print_width': '8.75in',
        'print_height': '11.25in',
    },
    'lulu_6x9': {
        'name': 'Lulu 6x9',
        'trim_width_mm': 152.4,
        'trim_height_mm': 228.6,
        'trim_width_in': '6in',
        'trim_height_in': '9in',
        'description': 'Lulu 6×9 (152mm × 229mm)',
        'print_width': '6.25in',
        'print_height': '9.25in',
    },
    'royal': {
        'name': 'Royal',
        'trim_width_mm': 156,
        'trim_height_mm': 234,
        'trim_width_in': '156mm',
        'trim_height_in': '234mm',
        'description': 'Royal (156mm × 234mm)',
        'print_width': '162mm',
        'print_height': '240mm',
    },
    'demy': {
        'name': 'Demy',
        'trim_width_mm': 138,
        'trim_height_mm': 216,
        'trim_width_in': '138mm',
        'trim_height_in': '216mm',
        'description': 'Demy (138mm × 216mm)',
        'print_width': '144mm',
        'print_height': '222mm',
    },
    'custom': {
        'name': 'Custom',
        'trim_width_mm': None,
        'trim_height_mm': None,
        'trim_width_in': None,
        'trim_height_in': None,
        'description': 'Custom size (use --trim-width and --trim-height)',
        'print_width': None,
        'print_height': None,
    }
}

# LaTeX code templates
PREAMBLE_TEMPLATE = r'''
% ---- PRINT STANDARDS (Auto-generated by latex_print_standards.py) ----
% Generated on: {date}
% Format: {format_name}
% Trim: {trim_width} × {trim_height}
% Bleed: {bleed}
% Safe Zone: {safezone}

\usepackage[%
  paperwidth={print_width},
  paperheight={print_height},
  margin={safezone},
  top={top_margin},
  bottom={bottom_margin},
  includehead,
  includefoot
]{{geometry}}

% Crop marks
\usepackage[cam,center]{crop}
\usepackage{graphicx}

\cropdef[frame]{{cropcam}}{{crop}}
\cropinfo{{Trim: {trim_width} × {trim_height} — Bleed: {bleed} — Safe Zone: {safezone}}}

% Visual trim guide (optional - remove for final print)
% Uncomment the following lines to show trim lines in the PDF
% \usepackage{{tickz}}
% \usepackage{{background}}
% \backgroundsetup{{
%   contents={{\begin{{tikzpicture}}[remember picture,overlay]
%     \draw[red!30, dashed, line width=0.5pt]
%       ([shift={{({bleed_cm},{-bleed_cm})}}]current page.south west) --
%       ([shift={{({bleed_cm},{bleed_cm})}}]current page.north west) --
%       ([shift={{({-bleed_cm},{bleed_cm})}}]current page.north east) --
%       ([shift={{({-bleed_cm},{-bleed_cm})}}]current page.south east) -- cycle;
%   \end{{tikzpicture}}}},
%   scale=1,
%   opacity=1,
%   angle=0
% }}

% ---- End Print Standards ----
'''


# =============================================================================
# Helper Functions
# =============================================================================

def parse_bleed(bleed_str):
    """Parse bleed string into value and unit."""
    if bleed_str.endswith('mm'):
        return float(bleed_str[:-2]), 'mm'
    elif bleed_str.endswith('in'):
        return float(bleed_str[:-2]), 'in'
    else:
        return float(bleed_str), 'mm'


def parse_margin(margin_str):
    """Parse margin string."""
    if margin_str.endswith('mm'):
        return margin_str
    elif margin_str.endswith('in'):
        return margin_str
    else:
        return f"{margin_str}mm"


def get_page_config(format_name, bleed_str, safezone_str):
    """Get page configuration for a given format."""
    config = PAGE_SIZES.get(format_name, PAGE_SIZES['a4'])
    
    if format_name == 'custom':
        # For custom, use provided values or fallback
        return config
    
    bleed_val, bleed_unit = parse_bleed(bleed_str)
    safezone = parse_margin(safezone_str)
    
    # Calculate bleed in the same unit as trim
    if bleed_unit == 'mm':
        bleed_prefix = ''
        bleed_suffix = 'mm'
        bleed_cm = bleed_val / 10
    else:
        bleed_prefix = ''
        bleed_suffix = 'in'
        bleed_cm = bleed_val * 2.54
    
    return {
        'name': config['name'],
        'format_name': format_name,
        'trim_width': config['trim_width_in'] if 'in' in str(config['trim_width_in']) else config['trim_width_in'],
        'trim_height': config['trim_height_in'] if 'in' in str(config['trim_height_in']) else config['trim_height_in'],
        'print_width': config['print_width'],
        'print_height': config['print_height'],
        'bleed': bleed_str,
        'bleed_cm': f"{bleed_cm:.2f}cm" if bleed_unit == 'mm' else f"{bleed_val:.2f}in",
        'safezone': safezone,
        'top_margin': safezone,
        'bottom_margin': safezone,
    }


def detect_document_class(content):
    """Detect the document class from the content."""
    match = re.search(r'\\documentclass(?:\[[^\]]*\])?\{([^}]+)\}', content)
    if match:
        return match.group(1)
    return 'article'


def detect_existing_geometry(content):
    """Check if geometry package is already loaded."""
    return bool(re.search(r'\\usepackage\[[^\]]*\]\{geometry\}', content))


def detect_existing_crop(content):
    """Check if crop package is already loaded."""
    return bool(re.search(r'\\usepackage\[[^\]]*\]\{crop\}', content))


def insert_preamble(content, page_config, verbose=False):
    """Insert print standards into the preamble."""
    preamble = PREAMBLE_TEMPLATE.format(
        date=datetime.now().strftime('%Y-%m-%d %H:%M'),
        format_name=page_config.get('name', 'Custom'),
        trim_width=page_config.get('trim_width', ''),
        trim_height=page_config.get('trim_height', ''),
        print_width=page_config.get('print_width', ''),
        print_height=page_config.get('print_height', ''),
        bleed=page_config.get('bleed', '3mm'),
        bleed_cm=page_config.get('bleed_cm', '0.3cm'),
        safezone=page_config.get('safezone', '6mm'),
        top_margin=page_config.get('top_margin', '6mm'),
        bottom_margin=page_config.get('bottom_margin', '6mm'),
    )
    
    # Find where to insert the preamble
    # Option 1: After \documentclass
    docclass_match = re.search(r'(\\documentclass(?:\[[^\]]*\])?\{[^}]+\})', content)
    if docclass_match:
        end_pos = docclass_match.end()
        # Check if there are packages already loaded
        after_docclass = content[end_pos:end_pos+100]
        # Insert after documentclass, before any \usepackage
        before = content[:end_pos]
        after = content[end_pos:]
        return before + '\n' + preamble + after
    
    # Option 2: At the very beginning
    return preamble + '\n' + content


def inject_geometry_settings(content, page_config, verbose=False):
    """Inject geometry settings into existing geometry package."""
    # If geometry is already loaded, we need to modify the existing line
    if detect_existing_geometry(content):
        # Find the geometry line
        geo_pattern = r'(\\usepackage)(\[[^\]]*\])?(\{geometry\})'
        match = re.search(geo_pattern, content)
        if match:
            old_opts = match.group(2) or ''
            # Build new options
            new_opts = [
                f'paperwidth={page_config["print_width"]}',
                f'paperheight={page_config["print_height"]}',
                f'margin={page_config["safezone"]}',
                f'top={page_config["top_margin"]}',
                f'bottom={page_config["bottom_margin"]}',
                'includehead',
                'includefoot'
            ]
            
            # Remove old options that conflict
            for opt in ['paperwidth', 'paperheight', 'margin', 'top', 'bottom']:
                old_opts = re.sub(rf',?\s*{opt}=[^,]+', '', old_opts)
            
            new_opts_str = ','.join(new_opts)
            if old_opts:
                # Merge with existing options
                old_opts_clean = old_opts.strip('[],')
                final_opts = f"[{old_opts_clean},{new_opts_str}]"
            else:
                final_opts = f"[{new_opts_str}]"
            
            return content.replace(match.group(0), f'\\usepackage{final_opts}{{geometry}}')
    
    return content


def inject_crop_settings(content, verbose=False):
    """Inject crop package settings."""
    if detect_existing_crop(content):
        # Modify existing crop line
        crop_pattern = r'(\\usepackage)(\[[^\]]*\])?(\{crop\})'
        match = re.search(crop_pattern, content)
        if match:
            old_opts = match.group(2) or ''
            if 'cam' not in old_opts and 'center' not in old_opts:
                if old_opts:
                    new_opts = old_opts.rstrip(']') + ',cam,center]'
                else:
                    new_opts = '[cam,center]'
                return content.replace(match.group(0), f'\\usepackage{new_opts}{{crop}}')
    return content


def main():
    parser = argparse.ArgumentParser(
        description='Add print standards (bleed, crop marks) to LaTeX documents.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python latex_print_standards.py mydoc.tex --format a4
  python latex_print_standards.py mydoc.tex --format us_letter --bleed 0.125in
  python latex_print_standards.py mydoc.tex --format drivethru_6x9 --safezone 0.25in
  python latex_print_standards.py mydoc.tex --format custom --trim-width 6in --trim-height 9in
        """
    )
    
    parser.add_argument('input', help='Input LaTeX file')
    parser.add_argument('--format', choices=list(PAGE_SIZES.keys()), default='a4',
                        help='Page format (default: a4)')
    parser.add_argument('--bleed', default='3mm',
                        help='Bleed size (e.g., 3mm, 0.125in) (default: 3mm)')
    parser.add_argument('--safezone', default='6mm',
                        help='Safe zone margin (e.g., 6mm, 0.25in) (default: 6mm)')
    parser.add_argument('--trim-width', help='Custom trim width (for --format custom)')
    parser.add_argument('--trim-height', help='Custom trim height (for --format custom)')
    parser.add_argument('--output', '-o', help='Output filename (default: input_printed.tex)')
    parser.add_argument('--titlepage', action='store_true',
                        help='Add a properly formatted title page')
    parser.add_argument('--no-cropmarks', action='store_true',
                        help='Disable crop marks')
    parser.add_argument('--book', action='store_true',
                        help='Use book class instead of article')
    parser.add_argument('--fontsize', default='11pt',
                        help='Font size (default: 11pt)')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Print verbose output')
    parser.add_argument('--dry-run', action='store_true',
                        help='Show what would be changed without writing')
    
    args = parser.parse_args()
    
    # Read input file
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: File not found: {args.input}")
        sys.exit(1)
    
    with open(input_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    if args.verbose:
        print(f"Reading: {args.input}")
        print(f"Format: {args.format}")
        print(f"Bleed: {args.bleed}")
        print(f"Safe Zone: {args.safezone}")
    
    # Get page configuration
    if args.format == 'custom':
        if not args.trim_width or not args.trim_height:
            print("Error: --trim-width and --trim-height required for custom format")
            sys.exit(1)
        page_config = {
            'name': 'Custom',
            'format_name': 'custom',
            'trim_width': args.trim_width,
            'trim_height': args.trim_height,
            'print_width': f"{args.trim_width} + {args.bleed}",
            'print_height': f"{args.trim_height} + {args.bleed}",
            'bleed': args.bleed,
            'safezone': args.safezone,
            'top_margin': args.safezone,
            'bottom_margin': args.safezone,
        }
    else:
        page_config = get_page_config(args.format, args.bleed, args.safezone)
    
    if args.verbose:
        print(f"Trim: {page_config.get('trim_width', 'custom')} × {page_config.get('trim_height', 'custom')}")
        print(f"Print: {page_config.get('print_width', 'custom')} × {page_config.get('print_height', 'custom')}")
    
    # Add title page if requested
    if args.titlepage:
        titlepage = r"""
\begin{titlepage}
  \centering
  \vspace*{2in}
  {\Huge\bfseries \textsc{Fate's Edge}}\\[0.5in]
  {\Large A Complete Guide}\\[0.2in]
  {\large Nicholas A. Gasper}\\[0.2in]
  {\large June 2026}
  \vfill
  {\large \textit{"The coin that never spends is the one you don't remember taking."}}
\end{titlepage}
"""
        # Insert after \begin{document}
        content = re.sub(r'(\\begin\{document\})', r'\1\n' + titlepage, content)
    
    # Detect document class and maybe change it
    doc_class = detect_document_class(content)
    if args.book and doc_class == 'article':
        content = content.replace(r'\documentclass{article}', r'\documentclass{book}')
        if args.verbose:
            print(f"Changed document class from article to book")
    
    # Insert print standards preamble
    content = insert_preamble(content, page_config, args.verbose)
    
    # Inject geometry settings if needed
    if detect_existing_geometry(content):
        content = inject_geometry_settings(content, page_config, args.verbose)
    
    # Inject crop settings if needed and not disabled
    if not args.no_cropmarks:
        content = inject_crop_settings(content, args.verbose)
    
    # Determine output filename
    if args.output:
        output_path = Path(args.output)
    else:
        stem = input_path.stem
        output_path = input_path.parent / f"{stem}_printed.tex"
    
    if args.dry_run:
        print("\n--- DRY RUN ---")
        print(f"Would write to: {output_path}")
        print(f"Changes would be made to:")
        print(f"  - Add geometry package with bleed settings")
        if not args.no_cropmarks:
            print(f"  - Add crop package with crop marks")
        if args.titlepage:
            print(f"  - Add title page")
        if args.book:
            print(f"  - Change document class to book")
        print("\nFirst 50 lines of modified content:")
        print("-" * 40)
        print('\n'.join(content.split('\n')[:50]))
        print("-" * 40)
        print(f"Total lines: {len(content.splitlines())}")
        sys.exit(0)
    
    # Write output
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ Written to: {output_path}")
    print(f"   Format: {page_config.get('description', args.format)}")
    print(f"   Bleed: {args.bleed}")
    print(f"   Safe Zone: {args.safezone}")
    
    if args.verbose:
        print(f"   Lines: {len(content.splitlines())}")


if __name__ == '__main__':
    main()
